# Generated by Django 4.0.1 on 2022-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_gerais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado_geral',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo:'),
        ),
    ]
